### ISSUE TITLE
Lock layout is broken

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [auth0/Lock.Android#550] opened 2019-09-13 17:10 UTC
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

- [x] I have checked the [README](https://github.com/auth0/Lock.Android/blob/master/README.md) for this library.

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/Lock.Android/issues) and [PRs](https://github.com/auth0/Lock.Android/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

- [x] I am reporting this to the correct repository (consider [Auth0.Android](https://github.com/auth0/Auth0.Android) and [Lock](https://github.com/auth0/lock)).

### Environment

Please provide the following:

- Version of the Lock.Android used: 2.15.0
- Version of the Android used: 5.0
- Additional packages that might be affecting your instance: 
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.browser:browser:1.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.0.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    implementation 'androidx.media:media:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.1.0-alpha10'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'

### Reproduction

Just launch lock activity

Please include:

- Phone model used to test - emulator Android 5.0
- Code snippet or sample project that reproduces the bug
- Log files or stacktraces (redact/remove sensitive information)
- Screenshots, if helpful

![Screen Shot 2019-09-14 at 12 02 49 AM](https://user-images.githubusercontent.com/8066100/64881024-e0145700-d683-11e9-986d-bc48ef0631f7.png)
![image](https://user-images.githubusercontent.com/8066100/64881067-0508ca00-d684-11e9-8be6-3ca1999d7d7a.png)

**Comment by lbalmaceda** [comment] 2019-09-16 17:24
@MAX-POLKOVNIK  Are you able to reproduce this with the sample app included in this project?

**Comment by MAX-POLKOVNIK** [comment] 2019-09-18 03:08
@lbalmaceda  Yes. Still the same.
I think it is bug in 'com.google.android.material:material:1.1.0-alpha10'
Steps to reproduce:
1. Clone repository
2. Migrate to AndroidX
3. Change 'com.google.android.material:material:1.0.0' to 'com.google.android.material:material:1.1.0-alpha10'

**Comment by lbalmaceda** [comment] 2019-09-18 20:43
@MAX-POLKOVNIK but neither this library nor the sample app use that material dependency. 

I assume as well it can be an AndroidX problem as this SDK is using support libraries. Have you [enabled jetifier](https://developer.android.com/jetpack/androidx#using_androidx) for your project already?

**Comment by MAX-POLKOVNIK** [comment] 2019-09-19 02:46
@lbalmaceda Yes. Both are enabled. Dependency has appeared after migrating to AndroidX. It is replacement for support design library (https://developer.android.com/jetpack/androidx/migrate/artifact-mappings)

**Comment by lbalmaceda** [comment] 2019-09-19 17:42
Correct, migrating to Android X would make those changes. I asked if you have as well enabled jetifier because that's the recommendation for when you use dependencies in your app that have not yet been migrated to Android X, just like this one. If that is enabled and you're still running into those problems, I would attribute this to a bug in the library that is not yet stable (is marked as alpha). I suggest you open a bug report on their issue tracker.

**Comment by lbalmaceda** [comment] 2019-10-10 14:49
Closing this one now. The resolution is to [use Jetifier in your app](https://developer.android.com/jetpack/androidx). There are no plans to migrate this library to Android X yet.

**Closed by lbalmaceda** 2019-10-10 14:49 UTC

**Comment by BesatZardoshtCarfax** [comment] 2020-04-28 15:46
This issue is appear in the stable version of the material com.google.android.material:material:1.1.0
and with setting Jetifier true.

**Comment by lbalmaceda** [comment] 2020-04-29 20:43
👍 fixed on 2.19.0
