### ISSUE TITLE
Attempt to invoke virtual method 'com.auth0.core.Connection com.auth0.lock.Configuration.getDefaultDatabaseConnection()' on a null object reference

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock.Android#188] opened 2016-01-23 14:09 UTC
We are seeing this on a few devices in Crashlytics. Using version 1.11.0. Note we are seeing this on a few Android 5.0/5.0.2 devices.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity java.lang.NullPointerException: Attempt to invoke virtual method 'com.auth0.core.Connection com.auth0.lock.Configuration.getDefaultDatabaseConnection()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2491)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2564)
       at android.app.ActivityThread.access$800(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.auth0.core.Connection com.auth0.lock.Configuration.getDefaultDatabaseConnection()' on a null object reference
       at com.auth0.lock.fragment.DatabaseLoginFragment.onCreate(DatabaseLoginFragment.java:102)
       at com.auth0.lock.fragment.SocialDBFragment.onCreate(SocialDBFragment.java:42)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2037)
       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:154)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:289)
       at com.auth0.lock.LockActivity.onCreate(LockActivity.java:89)
       at android.app.Activity.performCreate(Activity.java:6068)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2564)
       at android.app.ActivityThread.access$800(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```

**Comment by hzalaz** [comment] 2016-08-08 13:40
Closed by #318

**Closed by hzalaz** 2016-08-08 13:40 UTC

**Comment by ulohani90** [comment] 2017-06-05 12:34
Still facing this issue. Using 'com.auth0.android:lock:1.16.+'.

**Comment by lbalmaceda** [comment] 2017-06-05 15:41
@ulohani90 any steps to reproduce it? I'd suggest you either try the latest v1 dependency which is `1.18.+` or to migrate to v2 if possible. --> `2.5.0`.

**Comment by ulohani90** [comment] 2017-06-06 05:20
@lbalmaceda okay, let me try with 1.18.+.

**Comment by ulohani90** [comment] 2017-06-15 10:07
Tried with 1.18.+. Still I am seeing some crashes in Crashlytics. I am not able to reproduce it at my end. But I do have the stack trace for the crash that Crashlytics has given me. 

**Exception java.lang.RuntimeException: Unable to start activity**
ComponentInfo{com.eventshigh.pulse/com.auth0.lock.LockActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.auth0.core.Connection com.auth0.lock.Configuration.getDefaultDatabaseConnection()' on a null object reference
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2434)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2494)
android.app.ActivityThread.access$900 (ActivityThread.java:153)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1347)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5451)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
arrow_drop_down

**Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.auth0.core.Connection com.auth0.lock.Configuration.getDefaultDatabaseConnection()' on a null object reference**
com.auth0.lock.fragment.DatabaseLoginFragment.onCreate (DatabaseLoginFragment.java:110)
com.auth0.lock.fragment.SocialDBFragment.onCreate (SocialDBFragment.java:42)
android.support.v4.app.Fragment.performCreate (Fragment.java:2180)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1244)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1528)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1595)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:2893)
android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:190)
android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:353)
com.auth0.lock.LockActivity.onCreate (LockActivity.java:91)
android.app.Activity.performCreate (Activity.java:6323)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1108)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2387)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2494)
android.app.ActivityThread.access$900 (ActivityThread.java:153)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1347)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5451)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by bartolkaruza** [comment] 2017-08-04 11:41
This is also happening for me on `com.auth0.android:lock:1.17.+'` the version that `react-native-lock` 0.6.0 is on.

Huawei P10 Android 7.0
