### ISSUE TITLE
Unable to resume activity

### ISSUE THREAD

**Issue by YShein** [auth0/Lock.Android#438] opened 2017-09-18 16:36 UTC
Hello, i received an issue from fabric.

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.example.package/com.auth0.android.provider.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.getBoolean(java.lang.String, boolean)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.getBoolean(java.lang.String, boolean)' on a null object reference
       at com.auth0.android.provider.AuthenticationActivity.launchAuthenticationIntent(AuthenticationActivity.java:95)
       at com.auth0.android.provider.AuthenticationActivity.onResume(AuthenticationActivity.java:73)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7101)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

SM-G955U with android 7
Lock 2.7.0
compileSdkVersion 25
minSdkVersion 21
targetSdkVersion 25
buildToolsVersion "25.0.3"

Also, we are using PasswordlessLockActivity, we don't have  AuthenticationActivity even in manifest.

**Comment by lbalmaceda** [comment] 2017-09-18 17:03
I couldn't reproduce it but adding a null check in [this line](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/provider/AuthenticationActivity.java#L95) won't hurt. That Activity's code is pretty simple, I don't understand how it would get there. Maybe the activity get's killed because of missing memory? I'll add an issue to that repo and review it later. If you find any repro steps feel free to add them there.
Thanks

**Comment by lbalmaceda** [comment] 2017-10-03 17:27
@YShein `AuthenticationActivity` is an inner activity declared by the library and used to handle the WebAuth flow. So this issue should happen when using a social connection. Besides using PasswordlessLock, do you have any other repro steps? Or can you at least share how you're configuring/launching lock?

**Comment by lbalmaceda** [comment] 2017-10-06 17:35
I'll close this as repro steps are missing. Ping me if you find a way to reproduce it.

**Closed by lbalmaceda** 2017-10-06 17:35 UTC
