### ISSUE TITLE
Occasional crash when logging in

### ISSUE THREAD

**Issue by steffandroid** [auth0/Lock.Android#154] opened 2015-12-14 12:26 UTC
Not been able to replicate this myself, but we're occasionally getting the following stacktrace through on our crash analytics:

```
Android: 5.1.1
Manufacturer: motorola
Model: Nexus 6
Date: Wed Dec 09 17:23:24 GMT+00:00 2015

java.lang.RuntimeException: Could not dispatch event: class com.auth0.core.Application to handler [EventHandler public void com.auth0.lock.LockActivity.onApplicationLoaded(com.auth0.core.Application)]: Can not perform this action after onSaveInstanceState
    at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
    at com.squareup.otto.Bus.dispatch(Bus.java:386)
    at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
    at com.squareup.otto.Bus.post(Bus.java:336)
    at com.auth0.lock.fragment.LoadingFragment$2.onSuccess(LoadingFragment.java:71)
    at com.auth0.lock.fragment.LoadingFragment$2.onSuccess(LoadingFragment.java:67)
    at com.auth0.api.internal.BaseRequest$1.run(BaseRequest.java:86)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
    at com.auth0.lock.LockActivity.onApplicationLoaded(LockActivity.java:195)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
    at com.squareup.otto.Bus.dispatch(Bus.java:384)
    ... 13 more
```

**Comment by hzalaz** [comment] 2016-08-08 13:42
Might be solved by #318. Reopen if it can reproduced

**Comment by ulohani90** [comment] 2017-02-21 05:36
This issue still seems to exist. Following stack trace from Firebase Crash console
Exception java.lang.RuntimeException: Could not dispatch event: class com.auth0.core.Application to handler [EventHandler public void com.auth0.lock.LockActivity.onApplicationLoaded(com.auth0.core.Application)]: Can not perform this action after onSaveInstanceState
com.squareup.otto.Bus.throwRuntimeException (Bus.java:456)
com.squareup.otto.Bus.dispatch (Bus.java:386)
com.squareup.otto.Bus.dispatchQueuedEvents (Bus.java:367)
com.squareup.otto.Bus.post (Bus.java:336)
com.auth0.lock.fragment.LoadingFragment$2.onSuccess (LoadingFragment.java:72)
com.auth0.lock.fragment.LoadingFragment$2.onSuccess (LoadingFragment.java:68)
com.auth0.api.internal.BaseRequest$1.run (BaseRequest.java:86)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6117)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)
arrow_drop_down
Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1832)
android.support.v4.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1850)
android.support.v4.app.BackStackRecord.commitInternal (BackStackRecord.java:643)
android.support.v4.app.BackStackRecord.commit (BackStackRecord.java:603)
com.auth0.lock.LockActivity.onApplicationLoaded (LockActivity.java:196)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.squareup.otto.EventHandler.handleEvent (EventHandler.java:89)
com.squareup.otto.Bus.dispatch (Bus.java:384)
com.squareup.otto.Bus.dispatchQueuedEvents (Bus.java:367)
com.squareup.otto.Bus.post (Bus.java:336)
com.auth0.lock.fragment.LoadingFragment$2.onSuccess (LoadingFragment.java:72)
com.auth0.lock.fragment.LoadingFragment$2.onSuccess (LoadingFragment.java:68)
com.auth0.api.internal.BaseRequest$1.run (BaseRequest.java:86)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6117)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

**Comment by lbalmaceda** [comment] 2017-02-21 17:26
@ulohani90 this should be fixed in `compile 'com.auth0.android:lock:1.18.+'`.

**Closed by lbalmaceda** 2017-02-21 17:26 UTC
