### ISSUE TITLE
ClassNotFoundException: com.auth0.android.lock

### ISSUE THREAD

**Issue by horsejockey** [auth0/Lock.Android#562] opened 2020-02-17 17:34 UTC
### Description

I was working on a new release when I noticed our lock login activity no longer loaded the email/password entry fields. It is just blank with the ability to toggle between log in and sign up but no thing in the content area above the submit button. (see screenshot)

The only error message I could find is the following one.

```
E/Parcel: Class not found when unmarshalling: com.auth0.android.lock.internal.configuration.Options
    java.lang.ClassNotFoundException: com.auth0.android.lock.internal.configuration.Options
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
        at android.os.Parcel.readParcelable(Parcel.java:2781)
        at android.os.Parcel.readValue(Parcel.java:2684)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getString(BaseBundle.java:1155)
        at android.content.Intent.getStringExtra(Intent.java:8111)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:724)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1511)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:603)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6645)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6519)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6510)
        at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10833)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126)
        at android.os.Binder.execTransact(Binder.java:739)
     Caused by: java.lang.ClassNotFoundException: com.auth0.android.lock.internal.configuration.Options
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827) 
        at android.os.Parcel.readParcelable(Parcel.java:2781) 
        at android.os.Parcel.readValue(Parcel.java:2684) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:232) 
        at android.os.BaseBundle.getString(BaseBundle.java:1155) 
        at android.content.Intent.getStringExtra(Intent.java:8111) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:724) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1511) 
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:603) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6645) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6519) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6510) 
        at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10833) 
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126) 
        at android.os.Binder.execTransact(Binder.java:739) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Reproduction

 I hadn't made very many changes so I reverted them one by one. This is what caused the problem for me.

Moving from `'com.google.android.material:material:1.0.0'`
to `'com.google.android.material:material:1.1.0'`

Reverting to the 1.0.0 version has fixed the issue for me so I am still able to release our next version but I'm not sure what that would have to do with the issue I am seeing.  Progaurd doesn't seem to be the problem because it happens in debug builds without progaurd files.  

I'm creating Lock this way and it has been working for a year or so now for many releases:

```
private fun createLock(): Lock {
        val account = Auth0(Auth0Constants.clientId, Auth0Constants.domain)
        account.isOIDCConformant = true
        return Lock.newBuilder(account, callback)
            //Customize Lock
            .withAudience(Auth0Constants.audience)
            .withScheme(Auth0Constants.scheme)
            .withScope(Auth0Constants.scope)
            .closable(true)
            .hideMainScreenTitle(true)
            .build(context)
    }
```

### Environment

Reproduced on Lock versions 2.14.1 and 2.17.1
min sdk version 21
target sdk version 29

![Screenshot_20200217-103245_tilt dev](https://user-images.githubusercontent.com/2307109/74675541-02e5f280-5171-11ea-8c6d-79e656199d60.jpg)

**Comment by lbalmaceda** [comment] 2020-02-18 22:19
It seems like that release of the `material` widgets broke that. Unfortunately, external dependency changes are out of our scope. If we all follow semver this shouldn't happen. 

Anyway, I'll give it a try and see if I can get it working with the version `1.1.0`.

**Comment by hazsetata** [comment] 2020-03-31 14:27
I ran into the same problem today - for now I also reverted back to 1.0.0 of `material`. 

I also found that if you disable signup (`builder.allowSignUp(false)`) then the login UI displays correctly even with 1.1.0 version of `material`.

**Comment by lbalmaceda** [comment] 2020-04-29 16:18
Should be fixed in the next release.

**Comment by palimad** [comment] 2020-08-07 12:30
Is this already fixed, happening to me as well. I do not use material library.

my build.gradle:
`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.hotovo.auth0test"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "https"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation ('com.auth0.android:lock:2.21.1')
}`

and MainActivity:
`import android.app.Activity
import android.os.Bundle
import android.util.Log
import androidx.annotation.Nullable
import com.auth0.android.Auth0
import com.auth0.android.lock.AuthenticationCallback
import com.auth0.android.lock.Lock
import com.auth0.android.lock.LockCallback
import com.auth0.android.lock.utils.LockException
import com.auth0.android.result.Credentials


class MainActivity : Activity() {
    private var lock: Lock? = null
    override fun onCreate(@Nullable savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Your own Activity code
        val auth0 = Auth0("XXX", "XXX")
        auth0.isOIDCConformant = true
        lock = Lock.newBuilder(auth0, callback)
                .withAudience("XXX") // ... Options
                .build(this)
        startActivity(lock?.newIntent(this));
    }

    public override fun onDestroy() {
        super.onDestroy()
        // Your own Activity code
        lock?.onDestroy(this)
        lock = null
    }

    private val callback: LockCallback = object : AuthenticationCallback() {
        override fun onAuthentication(credentials: Credentials?) {
            //Authenticated
        }

        override fun onCanceled() {
            //User pressed back
        }

        override fun onError(error: LockException?) {
            //Exception occurred
        }
    }
}`

I can click on "Sign in with Google" and proceed with sign-in but I do get " Class not found when unmarshalling: com.auth0.android.lock.internal.configuration.Options" error and no callback

**Comment by lbalmaceda** [comment] 2020-08-07 15:40
@palimad the issue reported related to a change in the tab view dependency, making the app fail as soon as those where shown. As you see in the comments above, when the tab was not shown (e.g. sign up mode disabled) the issue was not present. 

Now, where is the error happening? can you share a small recording of the flow you're trying?

**Comment by AlexandrSalin** [comment] 2020-10-08 17:47
have the same issue on android 10 only

2020-10-07 14:19:41.023 1014-2918/? E/Parcel: Class not found when unmarshalling: com.auth0.android.lock.internal.configuration.Options
    java.lang.ClassNotFoundException: com.auth0.android.lock.internal.configuration.Options
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1932)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
     Caused by: java.lang.ClassNotFoundException: com.auth0.android.lock.internal.configuration.Options
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8548) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1932) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690) 
        at android.os.Binder.execTransactInternal(Binder.java:1056) 
        at android.os.Binder.execTransact(Binder.java:1029) 
2020-10-07 14:19:41.024 1014-2918/? W/Bundle: Failed to parse Bundle, but defusing quietly
    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.auth0.android.lock.internal.configuration.Options
        at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1932)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)

  implementation 'com.auth0.android:lock:2.23.0'

any advice?

**Comment by lbalmaceda** [comment] 2020-10-08 21:05
@AlexandrSalin 👋  is this on a debug build or production? is proguard running for this? can you share the steps to reproduce the issue?

**Comment by AlexandrSalin** [comment] 2020-10-09 17:26
i changed build target version to 30 and app crash on android 10

  minifyEnabled false
  proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
  debugable -false

**Comment by lbalmaceda** [comment] 2020-11-04 16:17
@AlexandrSalin I tried to repro with the details you gave and I couldn't. I've pushed the project [here](https://github.com/lbalmaceda/ReproduceableSamplesAuth0/tree/master/LockSample) so you can test it on your side as well. I'm using a "Pixel 2 - API 30" (Android 10) emulator.

**Comment by lbalmaceda** [comment] 2021-03-16 12:37
Closing due to inactivity

**Closed** 2021-03-16 12:37 UTC
Labels: waiting for customer

**Comment by istgin** [comment] 2023-02-01 22:20
Happens occasionally on Samsung tablets.

possible fix:
Lock.java
`public Intent newIntent(@NonNull Context context) {
        Intent lockIntent = new Intent(context, LockActivityCustom.class);
        Bundle b = new Bundle();
        b.putParcelable(Constants.OPTIONS_EXTRA, options);
        lockIntent.putExtra("bundle", b);
        lockIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        return lockIntent;
    }`

LockActivity.java 
`
private boolean hasValidOptions() {
        Bundle b = getIntent().getBundleExtra("bundle");
        options = b.getParcelable(Constants.OPTIONS_EXTRA);
         ....
`
